version: "3.8"

networks:
  tpnetwork:
    external: true
    name: applications_tp_network

volumes:
  grafana-volume:

services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    restart: always
    privileged: true
    ports:
      - "8086:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/snap/docker/common/var-lib-docker:/var/lib/docker:ro
    networks:
      - tpnetwork

  prometheus:
    image: prom/prometheus:latest
    restart: always
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    networks:
      - tpnetwork

  grafana:
    image: grafana/grafana:latest
    restart: always
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_SECURITY_ALLOW_EXTERNAL_LOGIN: "true"
    ports:
      - "3080:3000"
    volumes:
      - grafana-volume:/var/lib/grafana
    networks:
      - tpnetwork
